// GET OFFLINE VIDEOS
export const GET_OFFLINE_VIDEOS = 'GET_OFFLINE_VIDEOS';
export const GET_OFFLINE_VIDEOS_SUCCESS = 'GET_OFFLINE_VIDEOS_SUCCESS';
export const GET_OFFLINE_VIDEOS_FAIL = 'GET_OFFLINE_VIDEOS_FAIL';

// SEARCH YOUTUBE VIDEOS
export const SEARCH_VIDEOS = 'SEARCH_VIDEOS';
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAIL = 'SEARCH_VIDEOS_FAIL';

// GET CHANNEL VIDEOS
export const GET_CHANNEL_VIDEOS = 'GET_CHANNEL_VIDEOS';
export const GET_CHANNEL_VIDEOS_SUCCESS = 'GET_CHANNEL_VIDEOS_SUCCESS';
export const GET_CHANNEL_VIDEOS_FAIL = 'GET_CHANNEL_VIDEOS_FAIL';

// DOWNLOAD PROGRESS
export const SET_DOWNLOAD_PROGRESS = 'SET_DOWNLOAD_PROGRESS';

// DOWNLOAD YOUTUBE VIDEO
export const DOWNLOAD_VIDEO = 'DOWNLOAD_VIDEO';
export const DOWNLOAD_VIDEO_SUCCESS = 'DOWNLOAD_VIDEO_SUCCESS';
export const DOWNLOAD_VIDEO_FAIL = 'DOWNLOAD_VIDEO_FAIL';

// DELETE VIDEO FROM PHONE
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL';